### ISSUE TITLE
Compile error with Coq 8.7.1

### ISSUE THREAD

**Issue by codyroux** [mit-plv/kami#2]
I'm getting the following error on invoking `make` on the master branch:

> File "./Kami/ParamDup.v", line 501, characters 12-48:
> Error: No matching clauses for match.

I'm running Coq 8.7.1. The Readme mentions 8.6, and there's an 8.8 branch, but it's unclear to me whether 8.7 is supported or not.

**Comment by vmurali** [comment]
Right, 8.7 is not supported. The master branch compiles with 8.6(.1) and the 8.8 branch compiles with 8.8.

**Comment by codyroux** [comment]
Thanks!
